config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'games#index'
  resources :users, :sessions
  # get 'games/:id' => 'games#show', as: :games
  post '/saved_games' => 'saved_games#create', as: :saved_games
  get 'games' => 'games#index', as: :games
  get 'games/:id' => 'games#show', as: :game
  post '/friendships' => 'friendships#create'
  put '/friendships' => 'friendships#update'
  post 'games/:id/comments' => 'comments#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :classifications
  has_many :games, through: :classifications
end

app/models/classification.rb
class Classification < ApplicationRecord
  belongs_to :game
  belongs_to :category
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, foreign_key: :commenter_id
  has_many :votes, as: :votable
  belongs_to :game
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :accepting_friend, foreign_key: :accepting_id, class_name: "User"
  belongs_to :requesting_friend, foreign_key: :requesting_id, class_name: "User"

  validates_uniqueness_of :accepting_id, :scope => [:requesting_id]

end

app/models/game.rb
class Game < ApplicationRecord
  has_many :saved_games
  has_many :users, through: :saved_games
  has_many :classifications
  has_many :categories, through: :classifications
  has_many :votes, as: :votable
  has_many :comments
end

app/models/saved_game.rb
class SavedGame < ApplicationRecord
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, :hashed_password, presence: true
  validates :email, format: { with: /\A[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\z/ }

  has_many :comments, foreign_key: :commenter_id
  has_many :saved_games
  has_many :games, through: :saved_games
  has_many :accepted_friendships, foreign_key: :accepting_id, class_name: "Friendship"
  has_many :requested_friendships, foreign_key: :requesting_id, class_name: "Friendship"
  has_many :requests, through: :requested_friendships, source: :requesting_friend
  has_many :accepts, through: :accepted_friendships, source: :accepting_friend
  has_many :votes, foreign_key: :voter_id



  def password
    @password ||= BCrypt::Password.new(hashed_password)
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.hashed_password = @password
  end

  def is_friend(friend_id)
    friendships = friends_finder
    f = friendships.select do |friendship|
      friendship.accepting_id  == friend_id || friendship.requesting_id == friend_id
    end
    if f.length == 0
      return false
    else
      return true
    end
  end

  def friends_finder
    accepted_friendships + requested_friendships
    # friends = []
    # friends << self.accepted_friendships
    # friends << self.requested_friendships
    # friends
  end

  def accepted_friends
    friends_finder.select do |friendship|
      friendship.pending_request == false
    end
  end

  def authenticate(password)
    self.password == password
  end

  def accepted_friends
    return get_friends(false)
  end

  def pending_friends
    return get_friends(true)
  end

  private

    def get_friends(is_pending)

      #Select friendships that are either pending or accepted
      # based on whether parameter is_pending
      friendships = friends_finder.select do |friendship|
        friendship.pending_request == is_pending
      end

      #determine based on user who the friends are
      friends = friendships.map do |f|
        if f.accepting_id == id then
          f.requesting_friend
        else
          f.accepting_friend
        end
      end

      return friends
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user, foreign_key: :voter_id
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create

    # game_id = params[:id]

    # commenter_id = session[:users]

    if session[:users]
      @comment = Comment.new(body: params[:body], game_id: params[:id], commenter_id: session[:users])
      if @comment.save
        redirect_to "/games/#{params[:id]}"
      else
        #give errors and return to page
      end

    else
      redirect_to game_path
    end
  end

  private

  # def comment_params
  #   params.require(:comment).permit(:body, :game_id, :commenter_id)
  # end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    Friendship.create(params[:friends].permit!)
     redirect_to :controller => 'users', :action => 'show', id: session[:users]
  end

  def update
    pending = Friendship.find_by(requesting_id: params[:friends][:requesting_id],accepting_id: params[:friends][:accepting_id])
    pending.pending_request = false
    pending.save
    redirect_to :controller => 'users', :action => 'show', id: session[:users]
  end

  private
    def friendship_params
      params.require(:friendship).permit(:accepting_id, :requesting_id)
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end
end

app/controllers/saved_games_controller.rb
class SavedGamesController < ApplicationController
  def create
    @user = User.find(session[:users])
    user_id = @user.id
    game_id = params[:game_id]
    SavedGame.create(user_id: user_id, game_id: game_id)
    redirect_to @user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by(email: params[:user][:email])

    if @user
      if @user.authenticate(params[:user][:password])
        session[:users] = @user.id

        # redirect_to '/users/'+session[:users].to_s
        redirect_to :controller => 'users', :action => 'show', id: session[:users]
      else
        @errors = @user.errors.full_messages
        render "/sessions/new"
      end
    else
      @errors = ['login information must be valid']

      render "/sessions/new"
    end
  end

  def destroy
    session.delete(:users)
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
   @user = User.new(user_params)


   if @user.save
     session[:users] = @user.id

     redirect_to :controller => 'games', :action => 'index'
   else
     @errors = @user.errors.full_messages

     render'/users/new'
   end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    if session[:users]
      return true
    else
      return false
    end
  end

  def current_user
    if session[:users]
      return User.find(session[:users])
    else
      return nil
    end
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/saved_games_helper.rb
module SavedGamesHelper
  def saved_game?(game_id)
    @user = User.find(session[:users])
    games_ids = @user.saved_games.map {|saved_game| saved_game.game_id.to_i}
    games_ids.include?(game_id.to_i)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_comment.html.erb
<%= form_tag("/games/#{game.id}/comments", method: :post) do%>
  <%= text_field_tag :body, nil, placeholder: "enter comment" %>
  <%= submit_tag "Enter Comment" %>
<%end%>

app/views/application/_errors.html.erb
<% if @errors %>
  <% @errors.each do |error| %>
    <span class="errors"><%=error%></span><br />
  <% end %>
<% end %>

app/views/games/index.html.erb
<div class="game-list">
  <h2>Games</h2>
  <% @games.each do |game| %>
    <article id="game<%=game.id%>" class="game">
      <p><a href="/games/<%= game.id.to_s %>"><img src="<%= game.pic %>" width="200px" height="200px" alt="<%= game.name %>" /></a></p>
      <p class="game-title"><%= link_to game.name, game_path(game) %></p>
      <p class="game-title"><%= game.saved_games.count %> Saves
        <% if logged_in? %>
          <% if !saved_game?(game.id) %>
            <button><%= link_to 'save this game', saved_games_path(@saved_game, user_id: session[:users], game_id: game.id), method: :post %></button></p>
          <% end %>
        <% else %>
          <button><%= link_to 'save this game', new_session_path %></button></p>
        <% end %>
      </article>
  <% end %>
</div>

app/views/games/show.html.erb
<div id=game-show>
  <section class="game-info">
    <h2><%= @game.name %></h2>
      <br>
    <%= image_tag @game.pic, {class: "game", alt: @game.name + ' picture', width: '200px', height: '200px' } %>
      <br />
    <h3> Game Description:</h3>
    <%= @game.description%><br /><br />
    <span class="game-detail">Type of Game:</span>
    <%= @game.game_type %><br />
    <span class="game-detail">Game Duration (minutes):</span>
    <%= @game.duration %><br />
    <span class="game-detail">Number of Players:</span>
    <%= @game.players %><br />
  </section><br>

  <div class="save-game">
    <% if logged_in? %>
      <% if !saved_game?(@game.id) %>
        <button><%= link_to 'save this game', saved_games_path(@saved_game, user_id: session[:users], game_id: @game.id), method: :post %></button></p>
      <% end %>
    <% else %>
      <button><%= link_to 'save this game', new_session_path %></button></p>
    <% end %>
  </div>

  <section class="comments">
    <h3>Comments</h3>
    <div id="add-comment">
      <%= render partial: "comment", locals: {game: @game} %>
    </div>
    <ul>
      <% @game.comments.each do |comment| %>
        <li><%=comment.body%></li>
      <% end %>
    </ul>
  </section>
</div>

app/views/users/index.html.erb
<div class="user-list">
  <h2>Users</h2>
  <% @users.each do |user| %>
    <% if current_user == nil || logged_in? %>
      <p><%= link_to user.name, user_path(user) %> | <%= user.saved_games.count %> saved games
      <%if logged_in? %>
        <form  method='post' action='/friendships'>
          <input type="hidden"
         value="<%= form_authenticity_token() %>"
         name="authenticity_token"/>
          <input type="hidden" name="friends[requesting_id]" value='<%=current_user.id%>'>
           <input type="hidden" name="friends[accepting_id]" value='<%=user.id%>'>
           <% if current_user.id != user.id %>
            <button type="submit">Add Friend</button>
           <% end %>
        </form>
      <% end %>
    </p>
    <% end %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Registration</h1>
<%= render partial: 'errors' %>
<%=  form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
  <p> name:</br> <%= f.text_field :name%> </p>
  <p> Email:</br> <%= f.text_field :email%> </p>
  <p> Password:</br> <%= f.password_field :password%></p>
  <%= f.submit :Signup %>
<% end %>

app/views/users/show.html.erb
<div>
  <% if logged_in? %>
    <% if current_user.id == @user.id %>
      <div>
        <h1 class="title">Welcome, <%=@user.name %></h1>
      </div>

      <div>
        <h2>Your Saved Games</h2>
        <ul>
          <% @user.games.each do |game| %>
            <li><%= link_to game.name, game_path(game) %> | <%= game.saved_games.count %> saves</li>
          <% end %>
        </ul>
      </div>

      <div>
        <h2>Your Friends</h2>
        <ul>
          <% @user.accepted_friends.each do |friend| %>
            <li><%= link_to friend.name, user_path(friend) %> (<%=friend.games.count%> saved games)</li>
          <% end %>
        </ul>
      </div>

      <div>
        <h2>Pending Friend Requests</h2>
        <ul>
          <% @user.pending_friends.each do |friend| %>
            <li><%=friend.name%>  (<%=friend.games.count%> games)
                <form  method='post' action='/friendships'>
                  <input type='hidden' name="_method" value="put">
                  <input type="hidden" value="<%= form_authenticity_token() %>" name="authenticity_token"/>
                  <input type="hidden" name="friends[requesting_id]" value='<%=friend.id%>'>
                   <input type="hidden" name="friends[accepting_id]" value='<%=current_user.id%>'>
                   <button type="submit">Accept Friend</button>
                </form>
          <% end %>
        </ul>
      </div>
    <% elsif @user.is_friend(session[:users])  %>
            <div>
        <h1 class="title"><%=@user.name %>'s Profile Page</h1>
      </div>

      <div>
        <h2><%=@user.name %>'s Saved Games</h2>
        <ul>
          <% @user.games.each do |game| %>
            <li><%= link_to game.name, game_path(game) %> <%= game.saved_games.count %> Saves</li>
          <% end %>
        </ul>
      </div>
      <div>
        <h2><%=@user.name%>'s Friends</h2>
        <ul>
          <% @user.accepted_friends.each do |friend| %>
            <li><%= link_to friend.name, user_path(friend) %> (<%=friend.games.count%> saved games)</li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <form  method='post' action='/friendships'>
        <input type="hidden"
       value="<%= form_authenticity_token() %>"
       name="authenticity_token"/>
        <input type="hidden" name="friends[requesting_id]" value='<%=current_user.id%>'>
         <input type="hidden" name="friends[accepting_id]" value='<%=@user.id%>'>
         <button type="submit">Add Friend</button>
      </form>
    <% end %>
  <% else %>
    <h1>Please Login to view users</h1>
  <% end %>
</div>